services:
  landing-page:
    build: ./landing-page
    image: pundeepak/portfolio-landing-page:latest
    ports:
      - "80:80"
    restart: unless-stopped

  ui:
    build: ./ui
    image: pundeepak/portfolio-ui:latest
    ports:
      - "3000:80"
    restart: unless-stopped

  api:
    build: ./api
    image: pundeepak/portfolio-api:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  full-stack:
    build: ./full-stack
    image: pundeepak/portfolio-full-stack:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped